name = "XMLExample"
uuid = "bc3a10ed-ff8e-485c-874a-5c3ef0e3a543"
version = "0.1.0-dev"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]

[deps]
AnotherParser = "2ebba909-c633-4b8c-b8fe-948aaf993ef9"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
OrderedCollections = "1.8.2"
